% Wave Packet Dynamics
% Calculate etaPRIME for the Coulomb Interaction potential operator:
% dEta/dt = (9 * reduced_planck_const^2) / (4 * mass^2 * gamma^3) - ...
%                                                 partialV/partialGamma
% V = (-Ze^2 / q) * erf(sqrt(3/2) * q/gamma)
% --> partialV/partialGamma = (Ze^2) * sqrt(6/pi) * ...
%               e^[(-3*q^2)/(2*gamma^2)]

function etaPRIME_acc = compute_force_etaPRIME_coulombInteraction(etaPRIME_acc, num_particles, ...
    Z, reduced_planck_constant, mass, ...
    gamma, q_pos,...
    simulation_step)

    for particle_itr = 1:num_particles
       etaPRIME_acc(particle_itr, simulation_step) = ((9 * reduced_planck_constant * reduced_planck_constant) / ...
           (4 * mass * mass * ...
           gamma(particle_itr, simulation_step) * gamma(particle_itr, simulation_step) * gamma(particle_itr, simulation_step))) - ...
           (((Z*exp(2))/(gamma(particle_itr, simulation_step) * gamma(particle_itr, simulation_step))) * sqrt(6/pi) * ...
           exp((-3*q_pos(1:num_dimensions, particle_itr, simulation_step) * q_pos(1:num_dimensions, particle_itr, simulation_step)) / ...
           (2 * gamma(particle_itr, simulation_step) * gamma(particle_itr, simulation_step))));
    end
end