% Wave Packet Dynamics
% Calculate pPRIME for the Coulomb interaction potential operator:
% dp/dt = -del(q) * V
% V = (-Ze^2 / q) * erf(sqrt(3/2) * q/gamma)
% --> -del(q)V = Ze^2 * [(1/q*gamma) * sqrt(6/pi) *
% e^[(-3*q^2)/2*gamma^2)] - (1/q^2)*erf(sqrt(3/2)  * (q/gamma)]

function pPRIME_acc = compute_force_pPRIME_coulombInteraction(pPRIME_acc, num_dimensions, num_particles,...
    Z, q_pos, gamma,...
    simulation_step)

    for particle_itr = 1:num_particles
        % compute dp/dt at t
        pPRIME_acc(1:num_dimensions, particle_itr, simulation_step) = ...
            Z * exp(2) * ...
            ((((1/q_pos(1:num_dimensions, particle_itr, simulation_step)) * gamma(particle_itr, simulation_step)) * ...
            sqrt(6/pi) * exp((-3*q_pos(1:num_dimensions, particle_itr, simulation_step)^2)/(2*gamma(particle_itr, simulation_step)^2))) - ...
            ((1/q_pos(1:num_dimensions, particle_itr, simulation_step)^2) * ...
            erf(sqrt(3/2) * (q_pos(1:num_dimensions, particle_itr, simulation_step)/gamma(particle_itr, simulation_step)))));
    end
end
